apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parent-app
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      selfHeal: true
  source:
    path: my-app
    repoURL: https://github.ibm.com/essentials-core/ArgoCD-POC-Child-App1.git
    targetRevision: main
    helm:
      valueFiles:
      - values.yaml
