apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: child-app2
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      selfHeal: true
  source:
    path: Chail-app2/alpine
    repoURL: https://github.com/vvmanchala/ArgoCD-POC-Child-App2.git
    targetRevision: main
    helm:
      valueFiles:
      - values.yaml
